#!/usr/bin/env python3
"""Template-based report generation using Jinja2."""
import json
import os
import sys
from pathlib import Path

from jinja2 import Environment, FileSystemLoader


def load_data_files(data_dir: str) -> list[dict]:
    """Load all JSON data files from the data directory."""
    entities = []
    for filename in sorted(Path(data_dir).glob("*.json")):
        with open(filename) as f:
            entities.append(json.load(f))
    return entities


def collect_sources(entities: list[dict]) -> list[dict]:
    """Collect and deduplicate all sources from entity data."""
    seen_urls = set()
    sources = []
    for entity in entities:
        for src in entity.get("sources", []):
            url = src.get("url", "")
            if url and url not in seen_urls:
                seen_urls.add(url)
                sources.append(src)
    return sources


def build_comparison_table(entities: list[dict], field_names: list[str]) -> str:
    """Build a Markdown comparison table from entity data."""
    if not entities or not field_names:
        return ""
    header = "| Dimension | " + " | ".join(e["entity"] for e in entities) + " |"
    sep = "|---|" + "|".join("---" for _ in entities) + "|"
    rows = []
    for field in field_names:
        vals = []
        for entity in entities:
            entry = entity.get("fields", {}).get(field, {})
            val = entry.get("value", "N/A")
            if entry.get("uncertain"):
                val = f"{val} (?)"
            vals.append(str(val)[:80])
        rows.append(f"| {field} | " + " | ".join(vals) + " |")
    return "\n".join([header, sep, *rows])


def generate_comparison_report(
    topic: str,
    data_dir: str,
    templates_dir: str,
    field_names: list[str],
) -> str:
    """Generate a comparison report from entity JSON data."""
    entities = load_data_files(data_dir)
    sources = collect_sources(entities)
    table = build_comparison_table(entities, field_names)
    env = Environment(loader=FileSystemLoader(templates_dir))
    template = env.get_template("report_comparison.md")
    return template.render(
        topic=topic,
        executive_summary="[Generated by LLM orchestrator during Phase 6]",
        comparison_table=table,
        dimensions=[],
        entities=entities,
        recommendation="[Generated by LLM orchestrator during Phase 6]",
        sources=sources,
    )


def generate_evaluation_report(
    topic: str,
    data_dir: str,
    templates_dir: str,
    dimensions: list[dict],
) -> str:
    """Generate an evaluation report from dimension data."""
    entities = load_data_files(data_dir)
    sources = collect_sources(entities)
    env = Environment(loader=FileSystemLoader(templates_dir))
    template = env.get_template("report_evaluation.md")
    score = sum(
        d.get("score", 0) for d in dimensions
    )
    denom = max(len(dimensions), 1)
    overall = score // denom
    if overall >= 70:
        verdict = "Recommend"
    elif overall >= 50:
        verdict = "Conditional"
    else:
        verdict = "Not Recommended"
    return template.render(
        topic=topic,
        executive_summary="[Generated by LLM orchestrator during Phase 6]",
        dimensions=dimensions,
        overall_score=overall,
        risk_assessment="[Generated by LLM orchestrator during Phase 6]",
        verdict=verdict,
        verdict_rationale="[Generated by LLM orchestrator during Phase 6]",
        alternatives="[Generated by LLM orchestrator during Phase 6]",
        sources=sources,
    )


def generate_deep_report(
    topic: str,
    data_dir: str,
    templates_dir: str,
    sections: list[dict],
) -> str:
    """Generate a deep research report from section data."""
    entities = load_data_files(data_dir)
    sources = collect_sources(entities)
    env = Environment(loader=FileSystemLoader(templates_dir))
    template = env.get_template("report_deep.md")
    return template.render(
        topic=topic,
        executive_summary="[Generated by LLM orchestrator during Phase 6]",
        introduction="[Generated by LLM orchestrator during Phase 6]",
        sections=sections,
        synthesis="[Generated by LLM orchestrator during Phase 6]",
        limitations="[Generated by LLM orchestrator during Phase 6]",
        conclusion="[Generated by LLM orchestrator during Phase 6]",
        sources=sources,
        methodology="[Generated by LLM orchestrator during Phase 6]",
    )


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: generate_report.py <mode> <topic> <data_dir> [templates_dir]")
        print("Modes: comparison, evaluation, deep")
        sys.exit(1)
    mode, topic, data_dir = sys.argv[1], sys.argv[2], sys.argv[3]
    default_tpl = os.path.join(
        os.path.dirname(__file__), "..", "templates"
    )
    templates_dir = (
        sys.argv[4] if len(sys.argv) > 4 else default_tpl
    )
    if mode == "comparison":
        report = generate_comparison_report(topic, data_dir, templates_dir, [])
    elif mode == "evaluation":
        report = generate_evaluation_report(topic, data_dir, templates_dir, [])
    elif mode == "deep":
        report = generate_deep_report(topic, data_dir, templates_dir, [])
    else:
        print(f"Unknown mode: {mode}")
        sys.exit(1)
    print(report)
