#!/usr/bin/env zsh
cc_remote_stop
npm install -g @dianshuv/hapi

tmux new-session -d -s cc_remote -c ~/repos "hapi hub --tunnel"

echo "hapi hub started in tmux session 'cc_remote'"
echo "  attach: tmux attach -t cc_remote"
